apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-app2
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-app2
  template:
    metadata:
      labels:
        app: guestbook-app2
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-app2
        ports:
        - containerPort: 80
